#!/usr/bin/env python3
"""Generate a Bicep composition from a workload.yaml (ADR-0009).

Validates the manifest against schemas/workload.schema.json, maps
capabilities to governed br/platform modules, and writes main.bicep.
The output is not committed to service repos (ADR-0009).

Mapping today (platform-handbook #58):
  http      -> container-app-service (hosting)
  identity  -> container-app-service (its system-assigned managed identity)
  store     -> not yet supported
  queue     -> not yet supported

Usage:
  generate.py --manifest workload.yaml --out-dir out [--local-modules DIR]

--local-modules points the hosting module at DIR/<module>/main.bicep
instead of the registry pin, so CI can build without a published module.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

import yaml
from jsonschema import Draft202012Validator

GENERATOR_VERSION = "0.1.0"
ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schemas" / "workload.schema.json"

HOSTING_MODULE = "container-app-service"
SUPPORTED = {"http", "identity"}
NOT_YET_SUPPORTED = {"store", "queue"}
# Matches container-app-service's own `name` constraints (2-28 chars).
APP_NAME = re.compile(r"^[a-z][a-z0-9-]{1,27}$")
PIN = re.compile(r"^(?:br/platform:|br:ghcr\.io/aeroflow-air/)([a-z][a-z0-9-]*):(\d+\.\d+\.\d+)$")


class ManifestError(Exception):
    """A manifest the generator refuses. The message is shown to the caller."""


def load_manifest(path: Path) -> dict:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ManifestError(f"{path}: not valid YAML: {exc}") from exc
    validate(data)
    return data


def validate(data) -> None:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    errors = sorted(Draft202012Validator(schema).iter_errors(data), key=lambda e: list(e.absolute_path))
    if errors:
        lines = [f"  {'/'.join(map(str, e.absolute_path)) or '(root)'}: {e.message}" for e in errors]
        raise ManifestError("workload.yaml does not match the schema:\n" + "\n".join(lines))


def generate(manifest: dict, local_module_ref: str | None = None) -> str:
    """Return main.bicep for a schema-valid manifest.

    local_module_ref, when set, is the path (relative to the output file)
    of the hosting module's main.bicep, used instead of a registry pin.
    """
    caps = list(manifest["capabilities"])
    pending = [c for c in caps if c in NOT_YET_SUPPORTED]
    if pending:
        raise ManifestError(
            f"capability {', '.join(pending)} is not yet supported: no governed module exists "
            "(platform-handbook #58). Supported today: http, identity."
        )
    if "http" not in caps:
        raise ManifestError(
            "capabilities must include http: the only module today is container-app-service, "
            "which hosts an HTTP workload. identity on its own has nothing to attach to."
        )

    name = manifest["workload"]
    if not APP_NAME.match(name):
        raise ManifestError(
            f"workload '{name}' cannot name a container app: use 2-28 lowercase letters, "
            "numbers or hyphens, starting with a letter."
        )

    pin = (manifest.get("modules") or {}).get("hosting")
    if pin:
        match = PIN.match(pin)
        if not match or match.group(1) != HOSTING_MODULE:
            raise ManifestError(f"modules.hosting '{pin}' is not a {HOSTING_MODULE} pin; it is the only hosting module.")
    if local_module_ref is not None:
        ref = local_module_ref
    elif pin:
        ref = pin
    else:
        raise ManifestError(
            "modules.hosting is not set, and no module is published yet. "
            "Pin one (for example br/platform:container-app-service:0.1.0) or run with --local-modules."
        )

    source = "local stand-in, --local-modules" if local_module_ref is not None else "registry pin"
    return f"""// GENERATED by aeroflow-workflows generator {GENERATOR_VERSION} from workload.yaml. Do not edit or commit (ADR-0009).
// workload: {name}  repo: {manifest['repo']}  dataClass: {manifest['dataClass']}
// capabilities: {', '.join(caps)}
// hosting module: {HOSTING_MODULE} ({source})
targetScope = 'resourceGroup'

@description('Azure region. Defaults to the resource group location.')
param location string = resourceGroup().location

@description('Container image for the workload, supplied by the deploy step.')
param containerImage string

@description('HTTP ingress. Internal unless the deploy step asks for external.')
@allowed([
  'external'
  'internal'
])
param ingress string = 'internal'

// http + identity: one container app with a system-assigned managed identity.
module hosting '{ref}' = {{
  name: '{name}-hosting'
  params: {{
    name: '{name}'
    location: location
    containerImage: containerImage
    ingress: ingress
  }}
}}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--manifest", default="workload.yaml", type=Path)
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument("--local-modules", type=Path, help="folder holding <module>/main.bicep stand-ins")
    args = parser.parse_args(argv)

    try:
        manifest = load_manifest(args.manifest)
        local_ref = None
        if args.local_modules is not None:
            target = args.local_modules / HOSTING_MODULE / "main.bicep"
            if not target.is_file():
                raise ManifestError(f"no local stand-in at {target}")
            local_ref = Path(os.path.relpath(target.resolve(), args.out_dir.resolve())).as_posix()
        bicep = generate(manifest, local_ref)
    except ManifestError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)
    out = args.out_dir / "main.bicep"
    out.write_text(bicep, encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
