// GENERATED by aeroflow-workflows generator 0.1.0 from workload.yaml. Do not edit or commit (ADR-0009).
// workload: gate-allocation  repo: svc-gate-allocation  dataClass: confidential
// capabilities: http
// hosting module: container-app-service (registry pin)
targetScope = 'resourceGroup'

@description('Azure region. Defaults to the resource group location.')
param location string = resourceGroup().location

@description('Container image for the workload, supplied by the deploy step.')
param containerImage string

@description('HTTP ingress. Internal unless the deploy step asks for external.')
@allowed([
  'external'
  'internal'
])
param ingress string = 'internal'

// http + identity: one container app with a system-assigned managed identity.
module hosting 'br:ghcr.io/aeroflow-air/container-app-service:0.1.0' = {
  name: 'gate-allocation-hosting'
  params: {
    name: 'gate-allocation'
    location: location
    containerImage: containerImage
    ingress: ingress
  }
}
