// GENERATED by aeroflow-workflows generator 0.1.0 from workload.yaml. Do not edit or commit (ADR-0009).
// workload: flight-status  repo: svc-flight-status  dataClass: internal
// capabilities: http, identity
// hosting module: container-app-service (registry pin)
targetScope = 'resourceGroup'

@description('Azure region. Defaults to the resource group location.')
param location string = resourceGroup().location

@description('Container image for the workload, supplied by the deploy step.')
param containerImage string

@description('HTTP ingress. Internal unless the deploy step asks for external.')
@allowed([
  'external'
  'internal'
])
param ingress string = 'internal'

// http + identity: one container app with a system-assigned managed identity.
module hosting 'br/platform:container-app-service:0.1.0' = {
  name: 'flight-status-hosting'
  params: {
    name: 'flight-status'
    location: location
    containerImage: containerImage
    ingress: ingress
  }
}
